kind: Deployment
apiVersion: apps/v1
metadata:
  name: wangziweiddd
  namespace: dddops
  labels:
    app: wangziweiddd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wangziweiddd
  template:
    metadata:
      labels:
        app: wangziweiddd
    spec:
      containers:
        - name: wangziweiddd
          image: $REGISTRY/$DOCKERHUB_NAMESPACE/$PROJECT_NAME:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 1000m
              memory: 500Mi
            requests:
              cpu: 10m
              memory: 10Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
kind: Service
apiVersion: v1
metadata:
  name: wangziweiddd
  namespace: dddops
  labels:
    app: wangziweiddd
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080		#port:容器在service中暴露的端口(集群中可访问的端口)
      targetPort: 8080  #targetport:容器暴露的端口
      nodePort: 31000	#nodeport:容器在服务器中暴露的端口(外网可访问的端口)
  selector:
    app: wangziweiddd
  type: NodePort
  sessionAffinity: None
