server:
  port: 8080
spring:
  application:
    name: wangziweiddd
  datasource:
    username: root
    password: root
    url: jdbc:mysql://mysql-master.wzwddd:3306/people
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: redis.wzwddd
    port: 6379
    timeout: 30000
    lettuce:
      pool:
        max-active: 300
        max-idle: 8
        max-wait: -1
        min-idle: 0
mybatis:
  mapper-locations: classpath*:mybatis/*mapper.xml